### ISSUE TITLE
Captive Signing - Application crashed

### ISSUE THREAD

**Issue by Dinesh2871995** [docusign/native-ios-sdk#112]
When I am using captive signing, Docusign opening document, user able to sign but when he press finish, application gets crashed. Updated signed pdf updated of docusign but getting below crash everytime

```
let eManager =  DSMEnvelopesManager()
eManager.presentCaptiveSigning(withPresenting: vc, envelopeId: envelopeId, recipientClientUserId: "1", animated: true, completion: {a,b in
         print("completion block")
 })



 Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSBundle initWithURL:]: nil URL argument'
```

**Comment by mmohareb** [comment]
we will be looking into this issue soon, and will reply back to you.

**Comment by iOSSDK-DocuSign** [comment]
Ticket to document issue: https://jira.corp.docusign.com/browse/IOSSDK-1119

**Comment by mmohareb** [comment]
hello @Dinesh2871995 

we tried this flow on our side and the issue was NOT reproduced.
Our best guess from the crash reports, is that this is an issue with how the DocuSignSDK.bundle is linked (or missing link)
did you link the framework directly into your app, or did you use cocoapods?

Please refer to this guide on how to link the SDK directly in case you are not using cocoapods
https://developers.docusign.com/docs/ios-sdk/developer.html (Select **INTEGRATION** from side bar)

**Comment by mmohareb** [comment]
Closing issue.
