### ISSUE TITLE
How to resolve "Only role name allowed for in-person recipients" error when cache template

### ISSUE THREAD

**Issue by ThisIszas** [docusign/native-ios-sdk#126]
How to resolve "Only role name allowed for in-person recipients" error when cache template,  I added those 2 recipients in my template, but the `cacheTemplate` method always return this error.
<img width="1188" alt="image" src="https://user-images.githubusercontent.com/15715045/177104482-287aa126-7237-4463-9a5e-13a1b25d6b23.png">

Optional(Error Domain=template.save.error Code=0 "Only role name allowed for in-person recipients." UserInfo={NSLocalizedDescription=Only role name allowed for in-person recipients., NSLocalizedFailureReason=TEMPLATE_ERROR_INPERSON_ONLY_ROLE_ALLOWED})

**Comment by esilva600** [comment]
Hello,

Looking at the error message, apparently, the template has an in-person signer and the API call is using a different recipient type.
You need to provide the logs to The DocuSign Support Team, they can assist you.

You can check the article below on how to capture the logs:
https://support.docusign.com/s/document-item?language=en_US&rsc_301&bundleId=jux1643235969954&topicId=poz1578456669909.html&_LANG=enus

**Comment by ThisIszas** [comment]
Hi teams,

Log is attached, thanks for your reply.

[logs.zip](https://github.com/docusign/native-ios-sdk/files/9042662/logs.zip)

**Comment by ashokds** [comment]
Hi @ThisIszas ,



Following error is sent from iOS-SDK when it detects a template has `name`, `email` assigned to `signers` and `hosts` for offline use:
> "Only role name allowed for in-person recipients" 
 

I updated the screenshot to indicate how you could resolve this error:

<img width="1188" alt="only-role-name-allowed-error" src="https://user-images.githubusercontent.com/17131511/177380667-5a0234e9-d7c6-494f-87b8-5343841ff808.png">


In order to assign these properties to signers during offline template use on your app, you would need to use `DSMEnvelopeDefaults` and assign the `recipientDefaults` to provide `signers` and `hosts` details. Please take a look at (Using Envelope Defaults Guide)[https://github.com/docusign/native-ios-sdk/blob/master/Using-Envelope-Defaults.md] to understand various steps involved in creating an envelope with cached templates. Sample code from the linked guide is pasted here for quick reference: 

```
let recipientDefault = DSMRecipientDefault()

    // Use recipient roleName to find unique recipient in the template
    recipientDefault.recipientRoleName = "claimant-roleName"
    recipientDefault.recipientSelectorType = .recipientRoleName
    recipientDefault.recipientType = .inPersonSigner
    
    // In-person-signer name
    recipientDefault.inPersonSignerName = "Tom Wood"

    // Host name and email
    // If self hosting on the device, host name and email must match to logged-in account
    recipientDefault.recipientName = "docusignsdk user"
    recipientDefault.recipientEmail = "docusignsdk.user@dsxtr.com"

    // Set `true` to remove a recipient
    recipientDefault.removeRecipient = false

    let envelopeDefaults = DSMEnvelopeDefaults()
    envelopeDefaults.recipientDefaults = recipientDefault 
```

Thanks for posting this question.

**Comment by ThisIszas** [comment]
Thanks
