### ISSUE TITLE
Click API

### ISSUE THREAD

**Issue by MarvinNazari** [docusign/native-ios-sdk#139]
Hey, is there a support for using Click API with iOS SDK? Our backend handles creating a agreement url so signing can be done on the apps, it would be nice to have a support for this.

**Comment by MarvinNazari** [comment]
The use-case is kinda simple, a user can create a booking in our app and to be able to confirm the booking, they need to sign a contract, our backend then creates a agreement url for this user and returns it to the app, right now i need to open that link inside a `WKWebView` and give it the agreement url, and on callback when the user have signed it we close the browser in the app and show confirmation for booking. there is no need to API calls mostly, just a view controller that we can open with a agreement url and completion when it's finished or cancelled.

**Comment by mmohareb** [comment]
Thanks @MarvinNazari for your detailed explanation.
We don't expect to add support to this flow in our current SDK road map as we think that consumers of the SDK would still have to pass the url to the SDK and handle the call back from SDK, similar to what you are doing now with WKWebview.
Due to other priorities, we don't have any plans to add this feature in foreseeable future.
