### ISSUE TITLE
Misplacement noticed for signature fields in enveloped created via iOS

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#147]
HI @mmohareb 

Hope you are doing well.

We are using docusign for signing template but we have notice a different in place of envelope created from android and iOS. 

In android as they have online signing and in iOS we have Offline signing. It is working fine in Android while in iOS shifts toward upside which covers other fields as well.

I am attaching some reference document to docusignmobilesdk@docusign.com hope that will help you to debug.

Could you please look into this let me know if you have any quick fix for it?

 Thanks,
Pushpendra

**Comment by mmohareb** [comment]
Thanks @pushp1010 for raising this concern.
This is a known issue that we are hoping to address with the refactoring work underway to have parity across online and offline tag placement and also across different clients (iOS/Android/Web), but this work is still in progress and would not be addressed soon, will keep you posted once this concern is addressed.

For a quick workaround now, since you created the envelope on iOS you can add an offset to the tags locations to avoid them covering other fields and that should only impact the envelopes created from iOS while using the template on web or Android would not be impacted as the offset is only applied in iOS programmatically while building the envelope

for tabs that are not aligned use the `addFrame` method to adjust the location.
