### ISSUE TITLE
I am getting  DSMEnvelopeSyncingFailedNotification in our app

### ISSUE THREAD

**Issue by pushp1010** [docusign/native-ios-sdk#157]
Hi @mmohareb  @ashokds,

**Urgent help needed. We are getting below notification**

DSMEnvelopeSyncingFailedNotification is failing for user what can be the possible root cause of it?
NSConcreteNotification 0x281217480 {name = DSMEnvelopeSyncingFailedNotification; userInfo = {
    cacheURI = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
    envelopeId = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
    transactionId = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
}

When the envelope cache template is getting  cleared in Docusign SDK?
If one user is logged in and another time new user logged via SDK login  method will this clears the envelope cache? if no what are different ways to clear the envelope caches

**Comment by ashokds** [comment]
Hi @pushp1010 


You would need to call the SDK interface to remove the cached envelopes, as it's an action that ends up removing the envelope entirely and it's not possible to recover the data afterwards. In order to do so, you could use following:  

1. `DSMEnvelopesManager`: 

On [`DSMEnvelopesManager` there are two methods](https://docusign.github.io/native-ios-sdk/documentation/docusignsdk/dsmenvelopesmanager/removecachedenvelopewithid:) to remove the cached envelope(s).

```
- removeCachedEnvelopeWithId: 

- removeCachedEnvelopes
``` 

2. `DSMManager`:

You could use `logout` method on `DSMManager` when the old user logs out to clear the states - This also removes the cached envelopes.
```
/*!
 @method logout
 @abstract logout and clean/delete all local storage and user data. Note: Invoking this method will also remove any of the offline signed envelopes.
 @result boolean representing success with logout
 @see DSMEnvelopesManager to manage cached envelopes
 @see DSMTemplatesManager to manage cached templates
 */
+ (BOOL)logout;
```

Thanks.

**Comment by pushp1010** [comment]
@ashokds  Thanks for the quick response 

Could you please elaborate on DSMEnvelopeSyncingFailedNotification called scenarios ?
DSMEnvelopeSyncingFailedNotification is failing for a user what can be the possible root cause of it?

NSConcreteNotification 0x281217480 {name = DSMEnvelopeSyncingFailedNotification; userInfo = {
cacheURI = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
envelopeId = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
transactionId = "8B80AFDA-2026-46FD-9E12-47723FD5B0D6";
}

**Comment by ashokds** [comment]
@pushp1010 : `DSMEnvelopeSyncingFailedNotification` is sent when server rejects the payload. It could happen because of a number of reasons, such as:
- Missing signing info from the local signer. This is more prominent when there are multiple local signers and one of them is in-complete. SDK allows partial signed envelopes to be saved, and such envelopes could be resumed again. A partially signed envelope example is when 1 out of 2 local signers in current routing order completed signing, and then opt for Saving the envelope. 
- Incorrect Tab or unsupported property added to the offline envelope. This is also a common use-case when configuring local envelopes for signing.
- If the account isn't setup correctly for the Offline-Signing. This is a common use-case when multiple accounts are used or a new account is configured.

My recommendation is to capture the network log and share the request/response associated with the `Put/Post envelopes/recipients` calls. You could use Proxyman or Charles-Proxy to do that. 

Thanks,

**Comment by ashokds** [comment]
FYI: Edited above comment to include examples.

**Comment by ashokds** [comment]
Hi @pushp1010 : Closing this ticket as it has been answered.
