### ISSUE TITLE
"Asset validation failed" due to bitcode

### ISSUE THREAD

**Issue by tieulac305** [docusign/native-ios-sdk#174]
Hi!
I'm unable to upload my app to App Store Connect. I am using Swift, XCode 16.
Code compile and run well on device but I couldn't upload my app due to following reason:

2024-09-27 04:42:39 +0000 [MT] Validation for archive {App} had issues:
(
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90482 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Executable. The executable '{App}.app/Frameworks/DocuSignAPI.framework/DocuSignAPI' contains bitcode. (ID: e068ab93-f85c-4233-a957-17d6543e8330)})>",
    "<IDEDistributionIssue: severity(error), error(Error Domain=ContentDelivery Code=90482 \"Asset validation failed\" UserInfo={IDEDistributionIssueSeverity=3, NSLocalizedDescription=Asset validation failed, NSLocalizedRecoverySuggestion=Invalid Executable. The executable '{App}.app/Frameworks/DocuSignSDK.framework/DocuSignSDK' contains bitcode. (ID: 67b07ef7-9e73-494c-b806-f770761b1a82)})>"
)

Please take a look at this problem.
Thanks.

**Comment by mmohareb** [comment]
hello @tieulac305 
can you share how you integrated the DocuSignSDK with you project?
Also which version of the SDK are you using?
Bitcode support has been deprecated since xcode 14 https://developer.apple.com/documentation/Xcode-Release-Notes/xcode-14-release-notes#Deprecations
All our SDK releases since 3.0.0 have not used bitcode
