### ISSUE TITLE
Signing document in iOS Application

### ISSUE THREAD

**Issue by sparks2209** [docusign/native-ios-sdk#47]
Hi,

Is there a way where i can open pdf document in iOS application bundle and give signature.

I looked at examples most of them are creating template in DocuSign portal and using TemplateID.

In my case my document will be iPhone app and user need to sign the document and same need to be saved to bundle.

Thanks

**Comment by LarryKlugerDS** [comment]
I have asked our engineering group to respond to your question. I'm sorry for the slow response, we're changing our processes to speed things up for the future.

**Comment by ashokds** [comment]
@sparks2209 ,


iOS-SDK supports using pdf documents to start composing the envelopes to get signatures. The catch is that it requires the pdf-documents to be present in the Files app, and it presents an SDK UI component to add pdf-documents, recipients, and other details to initiate an envelope for capturing a signature. Here is the UI component you would see if you use `presentComposeEnvelopeController(with presentingController:..)`.

<img width="435" alt="Screen Shot 2020-11-03 at 10 18 59 PM" src="https://user-images.githubusercontent.com/17131511/98077082-61005600-1e24-11eb-8b7d-e21696e8d1b5.png">

^ Once all relevant details are filled in the above component without any error; pressing `Next` will launch the signing for any local signer. Otherwise, it'll send the envelope to remote recipients. 

From more details take a look at `DSMEnvelopesManager.h`:

```
/*!
 * @discussion Start creating an envelope to manually add documents, recipients and tags. Client app is responsible for detecting network to present view controller.
 * @param presentingController controller will be presented on top of the given presentingController passed.
 * @param signingMode compose envelope in either online or offline mode, see DSMSigningMode
 * @param resumeWithDraft determines whether to initialize flow with a previously saved draft (if any)
 * @param animated if the presentation of sign and send be animated or not.
 * @param completion block to be executed after compose envelope controller has been presented.
 * @warning passing nil to a presentationController will not be able to load the offline envelope flow.
 * @discussion Relevant Notifications that can be used to track the progress of an envelope sync task: DSMEnvelopeOnlineSendFailedNotification.
 * @see DSMNotificationCodes
 */
- (void)presentComposeEnvelopeControllerWithPresentingController:(UIViewController *)presentingController
                                                     signingMode:(DSMSigningMode)signingMode
                                                 resumeWithDraft:(BOOL)resumeWithDraft
                                                        animated:(BOOL)animated
                                                      completion:(nullable void(^)(UIViewController *_Nullable presentedController))completion;

```

**Comment by ashokds** [comment]
Closed because of age. Please reopen if still an issue.
